export const services = [
  {
    id: "01",
    title: "Gestión de Redes Sociales",
    description:
      "Construimos y gestionamos tu presencia en Instagram, Facebook, TikTok y LinkedIn. Estrategia de contenido, calendario editorial, diseño de piezas visuales y seguimiento de comunidad. Tú te dedicas a tu negocio; nosotros a que te vean.",
    tags: ["Instagram", "TikTok", "Contenido", "Comunidad"],
    color: "#5C6B8A",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776124935/06b5b5888a35b51a45b6de36e891b2eb_rkw5pk.mp4",
  },
  {
    id: "02",
    title: "Paid Media",
    description:
      "Campañas de Google Ads y Meta Ads estructuradas para rentabilidad, no para ego. No perseguimos la posición #1 que infla costos — apuntamos a las posiciones 2 y 3 donde están los prospectos listos para comprar. Cada peso invertido rinde resultados medibles.",
    tags: ["Google Ads", "Meta Ads", "ROI", "Performance"],
    color: "#2E4A7A",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776125071/b929285594b3e6e05299a118fc24c29a_1_osu9m0.mp4",
  },
  {
    id: "03",
    title: "Producción Audiovisual",
    description:
      "Un anuncio no convierte si no captura la atención en los primeros 3 segundos. Producimos videos cinemáticos, reels, fotografía profesional y tomas aéreas con dron. Hacemos que tu producto se vea premium antes de invertir un solo peso en publicidad.",
    tags: ["Video", "Fotografía", "Dron", "Reels"],
    color: "#8B6B52",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776125216/WhatsApp_Video_2026-04-12_at_9.24.39_PM_fbg6hb.mp4",
  },
  {
    id: "04",
    title: "Sitios Web & Landing Pages",
    description:
      "Un sitio web tradicional distrae; una landing page bien construida vende. Desarrollamos desde páginas corporativas hasta landing pages ultra-enfocadas, sin puntos de fuga, conectadas directamente a tu WhatsApp o CRM para que ningún prospecto se pierda.",
    tags: ["Sitio Web", "Landing Page", "UX/UI", "SEO"],
    color: "#2E5C4A",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776125164/7ae5d68a2a2f885d3cf7e4a1cd601d7c_720w_kmzzoi.mp4",
  },
];

export const projects = [
  {
    id: "01",
    year: "2025",
    title: "La Marea",
    services: ["Anuncios", "Creación de Contenido"],
    image: "/projects/la-marea.jpg",
    color: "#D4A574",
  },
  {
    id: "02",
    year: "2024",
    title: "Doroteo Querétaro",
    services: ["Creación de Contenido", "Anuncios"],
    image: "/projects/doroteo.jpg",
    color: "#8B7355",
  },
  {
    id: "03",
    year: "2025",
    title: "Genius Vending",
    services: ["Diseño Web"],
    image: "/projects/genius-vending.jpg",
    color: "#4A4A4A",
  },
  {
    id: "04",
    year: "2025",
    title: "Zenith Motors",
    services: ["Creación de Contenido", "Ads"],
    image: "/projects/zenith-motors.jpg",
    color: "#2C3E50",
  },
  {
    id: "05",
    year: "2025",
    title: "Turbos Amador",
    services: ["Diseño Web", "Creación de Contenido"],
    image: "/projects/turbos-amador.jpg",
    color: "#C0392B",
  },
  {
    id: "06",
    year: "2025",
    title: "Terraza Macarena",
    services: ["Agency", "Marketing"],
    image: "/projects/terraza-macarena.jpg",
    color: "#1ABC9C",
  },
];

export const clients = [
  { name: "Zenith Motors Puebla", status: "Activo" },
  { name: "Genius Vending Puebla", status: "Activo" },
  { name: "Turbos Amador Puebla", status: "Activo" },
  { name: "Terraza Macarena Querétaro", status: "Activo" },
];

export const heroImages = [
  {
    id: "001",
    label: "Restaurantes",
    alt: "Nicho restaurantes y CANIRAC",
    color: "#2E5C6A",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776102156/WhatsApp_Video_2026-03-19_at_12.43.20_PM_cbxwhl_r8x6vz.mp4",
  },
  {
    id: "002",
    label: "Automotriz",
    alt: "Nicho automotriz",
    color: "#1A1A1A",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776101065/Tesla2_vab5kh.mp4",
  },
  {
    id: "003",
    label: "Constructoras",
    alt: "Nicho constructoras",
    color: "#3A3A2E",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776101506/AQOOS8OB9cdG9kaqBJD4Gs3Q8rZq1-GKsZfuniEPiPESVZX7OajBffPjTXpxh2rc30fe375ZzfGXVoNT5k5unrVh5Ob-KmS5bydXwKA_dmffop.mp4",
  },
  {
    id: "004",
    label: "Bienes y Raíces",
    alt: "Nicho bienes y raíces",
    color: "#4A3A2E",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776101404/AQME_ZL8JHLV3ZEPxhls8z9L5hACmoU4uZazRTimqGjqvz0TZcr0j5U7UhvrzRatjjIdfDb0fmfT_-u-AHBn736ez7-xz-0BJOAdlE8_dj0apl.mp4",
  },
  {
    id: "005",
    label: "Eventos",
    alt: "Nicho de eventos",
    color: "#2E2A4A",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776101714/Reel_m2ftet.mp4",
  },
  {
    id: "006",
    label: "Servicios",
    alt: "Nicho servicios profesionales",
    color: "#1E2E1E",
    video: "https://res.cloudinary.com/dbqisatil/video/upload/v1776101274/AQPQOFP2CknFh7iZjtFDWRGeqLuiu-wE6o3L4EaKSH4XoEaxIAgPuWhJrRtB7CHuNDnCAdvL-XfWcEP_h32SaGdC627KoUHNg29_hbI_sjrjzm.mp4",
  },
];

export const paquetes = [
  {
    id: "inicial-1",
    categoria: "Paquete Inicial",
    nombre: "Esencial",
    precio: 7500,
    pauta: null,
    destacado: false,
    etiqueta: null,
    descripcion: "Ideal para negocios que están comenzando su presencia digital y necesitan establecer bases sólidas.",
    whatsappMsg: "Hola, me interesa el *Paquete Esencial* de PG Estrategias ($7,500/mes). Me gustaría recibir más información para comenzar.",
    features: [
      { label: "Creación u optimización de redes sociales, cuentas publicitarias y Google Business Profile", incluido: true },
      { label: "Estudio de buyer persona, cliente ideal y benchmarks", incluido: true },
      { label: "Estrategia digital personalizada", incluido: true },
      { label: "Reunión mensual de seguimiento", incluido: true },
      { label: "Creación u optimización + SEO de Landing Page", incluido: true },
      { label: "1 video de bienvenida", incluido: true },
      { label: "1 video para Meta Ads", incluido: true },
      { label: "4 horas de producción audiovisual", incluido: true },
      { label: "Gestión de redes sociales: 10 publicaciones (5 artes, 3 carruseles, 2 videos)", incluido: true },
      { label: "Reporte mensual de resultados", incluido: true },
    ],
    notas: ["No incluye costo de hosting ni dominio"],
  },
  {
    id: "inicial-1a",
    categoria: "Paquete Inicial",
    nombre: "Esencial Plus",
    precio: 11000,
    pauta: null,
    destacado: true,
    etiqueta: null,
    descripcion: "Para negocios que buscan acelerar su crecimiento con más contenido, branding y seguimiento más cercano.",
    whatsappMsg: "Hola, me interesa el *Paquete Esencial Plus* de PG Estrategias ($11,000/mes). Me gustaría recibir más información.",
    features: [
      { label: "Creación u optimización de redes sociales, cuentas publicitarias y Google Business Profile", incluido: true },
      { label: "Estudio de buyer persona, cliente ideal y benchmarks", incluido: true },
      { label: "Estrategia digital personalizada", incluido: true },
      { label: "Reunión quincenal de seguimiento", incluido: true },
      { label: "Creación u optimización + SEO de Landing Page", incluido: true },
      { label: "1 video de bienvenida", incluido: true },
      { label: "2 videos para Meta Ads", incluido: true },
      { label: "6 horas de producción audiovisual", incluido: true },
      { label: "Diseño de folletos y tarjetas de presentación", incluido: true },
      { label: "Gestión de redes sociales: 15 publicaciones (5 reels, 5 carruseles, 5 artes)", incluido: true },
      { label: "Diseño básico de logo y paleta de colores", incluido: true },
    ],
    notas: ["No incluye costo de hosting ni dominio"],
  },
  {
    id: "avanzado-promo",
    categoria: "Paquete Avanzado",
    nombre: "Impulso",
    precio: 11000,
    pauta: 2500,
    destacado: false,
    etiqueta: "Promoción",
    descripcion: "Paquete promocional que combina gestión orgánica con pauta publicitaria para empezar a escalar resultados.",
    whatsappMsg: "Hola, me interesa el *Paquete Impulso* de PG Estrategias ($11,000/mes + $2,500 en pauta incluida). Me gustaría recibir más información.",
    features: [
      { label: "Gestión de redes sociales: 12 publicaciones (4 artes, 3 carruseles, 3 reels)", incluido: true },
      { label: "Estrategia orgánica y parrilla de contenido", incluido: true },
      { label: "Gestión y creación de Meta Ads y Google Ads", incluido: true },
      { label: "Creación u optimización de redes sociales, cuentas publicitarias y Google Business Profile", incluido: true },
      { label: "Estudio de buyer persona, cliente ideal y benchmarks", incluido: true },
      { label: "1 sesión de hasta 6 horas de producción", incluido: true },
      { label: "Estrategia publicitaria basada en estudios incluidos", incluido: true },
      { label: "Reunión quincenal de seguimiento", incluido: true },
      { label: "Estrategia de programas de lealtad y posicionamiento en Google Search Console", incluido: true },
      { label: "Mensajería masiva hasta 850 mensajes al mes", incluido: true },
    ],
    notas: [
      "Incluye $2,500 MXN de pauta publicitaria",
      "No incluye costo de hosting ni dominio",
    ],
  },
  {
    id: "avanzado-2a",
    categoria: "Paquete Avanzado",
    nombre: "Escala",
    precio: 14000,
    pauta: 3000,
    destacado: true,
    etiqueta: null,
    descripcion: "Para negocios listos para escalar con mayor inversión publicitaria, más contenido y mensajería ampliada.",
    whatsappMsg: "Hola, me interesa el *Paquete Escala* de PG Estrategias ($14,000/mes + $3,000 en pauta incluida). Me gustaría recibir más información.",
    features: [
      { label: "Gestión de redes sociales: 12 publicaciones (4 artes, 4 carruseles, 4 reels)", incluido: true },
      { label: "Estrategia orgánica y parrilla de contenido", incluido: true },
      { label: "Gestión y creación de Meta Ads y Google Ads", incluido: true },
      { label: "Creación u optimización de redes sociales, cuentas publicitarias y Google Business Profile", incluido: true },
      { label: "Estudio de buyer persona, cliente ideal y benchmarks", incluido: true },
      { label: "1 sesión de hasta 6 horas de producción", incluido: true },
      { label: "Estrategia publicitaria basada en estudios incluidos", incluido: true },
      { label: "Reunión quincenal de seguimiento", incluido: true },
      { label: "Estrategia de programas de lealtad y posicionamiento en Google Search Console", incluido: true },
      { label: "Mensajería masiva hasta 1,400 mensajes al mes", incluido: true },
    ],
    notas: [
      "Incluye $3,000 MXN de pauta publicitaria",
      "No incluye costo de hosting ni dominio",
    ],
  },
  {
    id: "avanzado-2",
    categoria: "Paquete Avanzado",
    nombre: "Élite",
    precio: 27000,
    pauta: 7000,
    destacado: false,
    etiqueta: "Más completo",
    descripcion: "Solución integral para marcas que buscan dominar su mercado digital con máxima producción, pauta y estrategia.",
    whatsappMsg: "Hola, me interesa el *Paquete Élite* de PG Estrategias ($27,000/mes + $7,000 en pauta incluida). Me gustaría recibir más información.",
    features: [
      { label: "Gestión de redes sociales: 20 publicaciones (7 artes, 5 carruseles, 8 reels)", incluido: true },
      { label: "Estrategia orgánica y parrilla de contenido", incluido: true },
      { label: "Gestión y creación de Meta Ads y Google Ads", incluido: true },
      { label: "Creación u optimización de redes sociales, cuentas publicitarias y Google Business Profile", incluido: true },
      { label: "Estudio de buyer persona, cliente ideal y benchmarks", incluido: true },
      { label: "2 sesiones de hasta 6 horas de producción", incluido: true },
      { label: "Estrategia publicitaria avanzada en Google y Meta Ads", incluido: true },
      { label: "Reunión quincenal de seguimiento", incluido: true },
      { label: "Estrategia de programas de lealtad y posicionamiento en Google Search Console", incluido: true },
      { label: "Email marketing y mensajería masiva (hasta 2,500 mensajes al mes)", incluido: true },
    ],
    notas: [
      "Incluye $7,000 MXN de pauta publicitaria",
      "No incluye costo de hosting ni dominio",
    ],
  },
];

export const addOns = [
  {
    id: "sitio-web",
    nombre: "Sitio Web Inicial",
    descripcion: "Desarrollo de sitio web profesional desde cero, diseñado a medida para tu negocio.",
    precio: 3000,
    tipo: "unico",
    nota: "Pago único. No incluye hosting ni dominio.",
  },
];
